name: Download Models Directory

on:
  workflow_dispatch: # Allows manual trigger from the GitHub Actions UI

jobs:
  zip-models:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Forked Repository
      uses: actions/checkout@v4

    - name: Extract Short Commit SHA
      run: |
        echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    # Packages the DxDispatch/models directory directly into a ZIP archive
    - name: Upload Models Folder
      uses: actions/upload-artifact@v4
      with:
        name: dxdispatch-models-${{ env.SHORT_SHA }}
        path: DxDispatch/models/
        if-no-files-found: error
